---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170701090350"
editor:
  name: "StarterAdditionEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.4"
  origin:
    repo: "git@github.com:atomisthq/enrollment-rugs.git"
    branch: "d7ff35fdfb7e14247c9493a70801a7e47dbcb30c"
    sha: "d7ff35f"
  parameters:
    - "group": "org.springframework.boot"
    - "artifact": "spring-boot-starter-security"

